version: "3.9"

services:
  ai-rag-knowledge:
    container_name: ai-rag-knowledge
    build:
      context: ./wyj-dev-tech-app   # ← 指向含 Dockerfile 的目录
      dockerfile: Dockerfile
    image: system/ai-rag-knowledge:1.0
    # 如果应用监听 8080，建议这样；若确实是 8090，把两处都改成 8090
    ports:
      - "8090:8090"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    networks:
      - app-net
    # 可选：健康检查，保证 nginx 依赖可用
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health || curl -sf http://localhost:8080/"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-frontend
    depends_on:
      ai-rag-knowledge:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./dev-ops/release/nginx/html:/usr/share/nginx/html:ro
      - ./dev-ops/release/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro  # ← 带上 conf/
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net: