server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://106.54.0.161:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-TrhkYm25ovLPxrmQ859cBfA7A12f4d34A731A12e9891C773
      embedding-model: text-embedding-ada-002
    openai1:
      base-url: https://api.wahooai.com
      api-key: sk-3B1oEhNc0jYJ61G37e93759aC6C9403dAe33C9EdE83dAf93
      embedding-model: text-embedding-ada-002
    ollama:
      base-url: http://106.54.0.161:11434
      embedding:
        options:
          num-batch: 512
        model: nomic-embed-text
    rag:
      embed: nomic-embed-text #nomic-embed-text、text-embedding-ada-002
    vectorstore:
      pgvector:
        table-name: public.vector_store

# Redis
redis:
  sdk:
    config:
      host: 106.54.0.161
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
